> auth.http

@baseURL = http://localhost:3000/api/v1/media
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhYWJhemEzMkBnbWFpbC5jb20iLCJkZXZpY2VfaWQiOiIyZWRiY2RhNTgzOWRiNTVhYjIyNTJhMWVlNTg4ZTVjNCIsImlhdCI6MTczMTcwMTEyNCwiZXhwIjoxNzMxNzAxNzI0fQ.4x-_rloSRf5h46EUmBe_N5fvmaSWuRipMS7GfAtxxDo

### Upload Image
PUT  {{baseURL}}/images HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer {{access_token}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.jpg"
Content-Type: image/jpeg

< ../../../../../Downloads/00006_00.jpg 
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Upload Video
PUT  {{baseURL}}/movies HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer {{access_token}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="movie"; filename="movie.mp4"
Content-Type: video/mp4

< ../../../../../Downloads/00006_00.mp4
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Get all media
@page = 0
GET  {{baseURL}}/{{page}} HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json


### Delete media
@id = 1
DELETE  {{baseURL}}/{{id}} HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
